---
title: "AU_applied_machine_learning_health_science_notes"
format: pdf
editor: visual
---

# Questions

-   Is the book discussing lr as univariate or as multiple reg?
-   Are this mostly focused on tabular data?
-   Asses bias in data structure?
    -   Clinical assement - why data collection- systematic errors
-   Most ML methods i clinical medicine are used for prediction, are u familiar with examples of interpabele models with interest in inference?
-   Include conlinear pridictor in a model?
    -   depends on the question...
-   Can multiple linear regression differentiate between colinear predictors?
-   Evaluate linear vs non-linear?
- why using gaussian model to linear regression?

- Transfer learning
    - opnion on using this with low obs dataset?

# Reading Material

Intrduction to statistical learning website: www.statlearning.com

Online lecture: https://www.dataschool.io/15-hours-of-expert-machine-learning-videos/

# Day 1

## material

Read ISL: **1** Mulptiple factors predicts a certain outcome age, education, calendar date --\> wages - Use linear regression

Stock markets varaibility - Daily changes in a classification problem - Account for % change the previous days

Gene expression data

-   Genes clusters and disease outcomes

Vector are represented as columns with a specfic lenght

Matrices include a number of rows(n) and columns (p)

### 2 (intro), 2.1, 2.1.1-2.1.5, 2.2, 2.2.1-2.2.3

in f, we want to be able to predict Y as precisely as possible using X. However, often there are multiple X that affect the value of Y. Hence, combing dimensions of multiple X may increase the precision of the predicted Y. Still, erroe (residuals) will always be present, which is is inredductable in f(x). Methods in SL are therfore relevant to minimize error in f(x).

Whether the goal is predicition, inference or a combination of both, we have to use different methods to investigate these f. More complicated non-linear models might be better but the trade-off is interpability.

**Parametric methods**

two step model-based approach

1.  assumption about the functional form e.g. linear

2.  Select the prcedure for fit and training data.

    -   fit is mostly OLS

**Non-parametric method**

No assumption, models with more fitting ponits in predcition. Splines are introduced. - High risk of overfitting and the prediction will be detemined by errors rather than true patterns.

**3 (intro), 3.1, 3.1.1, 3.2, 3.2.1, 3.3.1, 3.3.2**

**5 (intro), 5.1, 5.1.1, 5.1.2, 5.1.3, 5.1.4**

**6.4, 6.4.1-6.4.4**

# Day 1 - Introduction, linear regression, model evaluation and resampling

LR works well with small datasets

## Excercise Day 1

### Introduction

**Check point 1: Supervised learning example**

*Example 1* Research questions: Could we predict HbA1c given various measurement of cholesterol, bmi, age, blood pressure, and sex.

Method: Linear regression

Data set: tabular data set with age, sex, body measures and biochemical measures.

*Example 2*

**Check point 2:**

Find part from ECG nodes in ECG data to detect early high risk of CVD event. Mixed inference and prediction. As ECG have large variability, I believe to include many recordings (\> 1000).

Methods: Deep learning neural network ?

Data: Time to event data - ECG data for each individuals - Hospital records of CVD events

### Supervised learning

Estimating a model:

-   Regression

    -   Linear regression
    -   Logistic regression

-   Classification

e.g. quantative response and predictor variable.

in linear regression the error terms is the term we cannot change.

model accuracy is base on the MSE_train and MSE_test - train based on defined model and test the error - test the trained model on the test dataset and observe MSE

#### Linear regression

Feature = variable

**Feature selection**

-   Based on expert knowledge of what to include
-   Include all slightly relevant features
    -   In the fitting process, we can improve model to great fit
-   The fitting should only be done in the training dataset

- OBS* Too many features can add too much noise in the prediction

*Suggestion:*

Expert model and machine learned determined models

-   test both to discuss.
    -   Best fitted model (overfit)
    -   Applicability

**Flexibility**

- Interaction terms
- Polynominal regression
    - d = 2-n
    
#### Bias variance decomposition

We want to reduce total error from model
- Decrease variance and bias
    - this is always a trade-off

- We want to achieve low bias low variance

